# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/giulia/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),giulia)

$(call add-radio-file-sha1-checked,radio/abl.img,5dadc071e21c7631c3da95398035a267735c2e7c)
$(call add-radio-file-sha1-checked,radio/aop.img,b92dce3e5029b2b568a47260a3e749210a75827d)
$(call add-radio-file-sha1-checked,radio/aop_config.img,53f418ae26e2014e7bdbd02f9903c2b2fb8cd9b7)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,c29af6e672547690228287e14959e402bef70d54)
$(call add-radio-file-sha1-checked,radio/cpucp.img,a1988270dd9d97fdd753d2f3357a18bb48707ad1)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,7ff7bdaf562ec17722a9b0860705f4ee4a193f7e)
$(call add-radio-file-sha1-checked,radio/devcfg.img,0e967c658d4b116359cd34561b5a35b3f202494e)
$(call add-radio-file-sha1-checked,radio/dsp.img,72075bb397712d2b7753e2a8654cf8e5c2313602)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,4dbceca34d16a280ce6c6a9b85f112499e853b8a)
$(call add-radio-file-sha1-checked,radio/hyp.img,e583d8c19c2caac1dc3999bdd10654f3258610b6)
$(call add-radio-file-sha1-checked,radio/imagefv.img,739c8235fdbd0e765fe8b9a6454bc571379fb312)
$(call add-radio-file-sha1-checked,radio/keymaster.img,35305eaa1e3f2dee647f8548a9700f02a5283ddc)
$(call add-radio-file-sha1-checked,radio/modem.img,8d2126ab0754297cec6f742f470f1b56f6693031)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,2b22c438931715f95882189e89e5db65981981ef)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,cd531ef38de2b3bf481b93c3c3f5c18f12d4280c)
$(call add-radio-file-sha1-checked,radio/qupfw.img,3ed51b87f4886f5bec9a87497252137e1e516875)
$(call add-radio-file-sha1-checked,radio/shrm.img,c9d02604eca8ec2264673fda7687cc8798ff9062)
$(call add-radio-file-sha1-checked,radio/splash.img,ba879350a23acffdfb0d14dd3b13f0401178525d)
$(call add-radio-file-sha1-checked,radio/tz.img,ff065c7953dad0fdc28c9f5666d6aa5c8bf48513)
$(call add-radio-file-sha1-checked,radio/uefi.img,f3c604f19a33519d3d28b3254ed8553f5660b5a3)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,7f413dda4b41656a9db74683662fa19d040d7bbb)
$(call add-radio-file-sha1-checked,radio/xbl.img,7a47376a4c4344b80e0be12fa742a08d945b29fe)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a9a1a1453dd51d0bae722dc9998b0d03962739ba)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,d26ce4b4963e129a82332914f8b43b39a0072abb)

endif