# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/giulia/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/giulia

PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/FTM/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/acdb_cal.acdb \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/FTM/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/workspaceFileXml.qwsp \
    vendor/oneplus/giulia/proprietary/odm/etc/acdbdata/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/acdb_cal.acdb \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/camera_engmode.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/camera_engmode.xml \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/camera_unit_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/camera_unit_feature_config.protobuf:$(TARGET_COPY_OUT_ODM)/etc/camera/config/camera_unit_feature_config.protobuf \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/imx355:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx355 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/imx480:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx480 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/imx906:$(TARGET_COPY_OUT_ODM)/etc/camera/config/imx906 \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_algo_switch_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_switch_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_algo_traversal_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_algo_traversal_config.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_aps_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_aps_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_camera_preview_decision_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_camera_preview_decision_config.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/oplus_preview_decision_params.json:$(TARGET_COPY_OUT_ODM)/etc/camera/config/oplus_preview_decision_params.json \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/s5kjn5_giulia:$(TARGET_COPY_OUT_ODM)/etc/camera/config/s5kjn5_giulia \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/quick_visibility_white_list:$(TARGET_COPY_OUT_ODM)/etc/camera/config/quick_visibility_white_list \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/video_beauty_default_config:$(TARGET_COPY_OUT_ODM)/etc/camera/config/video_beauty_default_config \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/config/pickref_params.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/config/pickref_params.xml \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/settings_fdc.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/settings_fdc_lite.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/settings_fdc_lite.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/display/qdcm_calib_data_AA577_P_3_A0020_dsc_cmd_mode_panel.json:$(TARGET_COPY_OUT_ODM)/etc/display/qdcm_calib_data_AA577_P_3_A0020_dsc_cmd_mode_panel.json \
    vendor/oneplus/giulia/proprietary/odm/etc/iris_configs.xml:$(TARGET_COPY_OUT_ODM)/etc/iris_configs.xml \
    vendor/oneplus/giulia/proprietary/odm/etc/iris_page_i7.json:$(TARGET_COPY_OUT_ODM)/etc/iris_page_i7.json \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Vivid_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Vivid_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Nature_2nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Nature_2nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EP3_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EP3_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Cinema_2nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Cinema_2nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Nature_100nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Nature_100nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EsRGB_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EsRGB_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/3D-Lut_StandardMode_P3.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/3D-Lut_StandardMode_P3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Cinema_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Cinema_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_2_2nit.odf$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_2_2nit.odf \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/3D-Lut_Stand_sRGB.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/3D-Lut_Stand_sRGB.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EsRGB_100nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EsRGB_100nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/3D-Lut_Stand_P3.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/3D-Lut_Stand_P3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_1_max.odf$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_1_max.odf \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_1_100nit.odf$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_1_100nit.odf \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_1_2nit.odf$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_1_2nit.odf \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_2_max.odf$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_2_max.odf \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/3D-Lut_Center_P3.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/3D-Lut_Center_P3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_2_100nit.odf$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_2_100nit.odf \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/panelchaplin$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/panelchaplin \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/3D-Lut_StandardMode_sRGB.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/3D-Lut_StandardMode_sRGB.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Cinema_100nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Cinema_100nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Vivid_2nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Vivid_2nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AdjustValue$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AdjustValue \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Nature_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Nature_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_LsRGB_100nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_LsRGB_100nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_HS$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_HS \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/Lut3D_311$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/Lut3D_311 \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/Lut3D_312$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/Lut3D_312 \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EP3_100nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EP3_100nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_LsRGB_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_LsRGB_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/3D-Lut_Enhance_P3.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/3D-Lut_Enhance_P3.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EP3_2nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EP3_2nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EsRGB_2nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_EsRGB_2nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/3D-Lut_Center_sRGB.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/3D-Lut_Center_sRGB.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_LsRGB_2nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_LsRGB_2nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/3D-Lut_Enhance_sRGB.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/3D-Lut_Enhance_sRGB.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Vivid_100nits_pGC.txt$(TARGET_COPY_OUT_ODM):/etc/PanelChaplin/AA577_P_3_A0020_dsc_cmd_mode_panel_Vivid_100nits_pGC.txt \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/json_list:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/json_list \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_ak09919.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_ak09919.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_alsps.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_alsps_hw_tcs3720.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_alsps_hw_tcs3720.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_bmp5_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_bmp5_0.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_cct_rear.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_cct_rear.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_freefall.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_freefall.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_icm4x6xx.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_icm4x6xx.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_mmc56x3x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_mmc56x3x.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_oplus_chop.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_oplus_chop.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_oplus_lay.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_oplus_lay.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_oplus_measurement.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_oplus_measurement.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_oplus_smart_prox.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_oplus_smart_prox.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lanai_mtp_pocket.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_pocket.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/lux_aod.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lux_aod.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/config/giulia_qrd_ois_system.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/giulia_qrd_ois_system.json \
    vendor/oneplus/giulia/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.b0a:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0a \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.b0c:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0c \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.b0e:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0e \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.b0i:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0i \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.elf \
    vendor/oneplus/giulia/proprietary/odm/etc/wifi/kiwi/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/regdb.bin \

    $(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/odm/firmware/tp,$(TARGET_COPY_OUT_ODM)/etc) \
    
PRODUCT_PACKAGES += \
    CFR_OPlus_EF017_UW_snapshot \
    CFR_imx355 \
    CFR_imx906 \
    CFR_s5kjn5_giulia

PRODUCT_PACKAGES += \
    acdb_cal_acdb_cal_symlink
